name: Update JSON Daily

on:
  schedule:
    - cron: "30 7 * * *" # Runs every day at 7:30 AM UTC

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Latest Data
        run: |
          curl -o raw.json "https://raw.githubusercontent.com/cabusto/nhl-graphql/refs/heads/main/raw.json" # Replace with your source

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add raw.json
          git commit -m "Updated JSON data"
          git push
